version: '3.8'

services:
    vite-app:
        image: node:20.18.1
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '5173:5173'
        command: sh -c "npm install && npm run dev -- --host"
